version: "3.5"
services:
  go-rest-web:
    platform: linux/amd64
    container_name: go-rest-web
    build:
      context: ./.dockers/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_rest_web
    ports:
      - "3320:3306"
    volumes:
      - ./.dockers/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
